name: Fetch API Data

on:
  push:
    branches:
      - master

jobs:
  fetch-api-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Fetch API Data
        run: node script.js  # Replace with the name of your JavaScript file
        env:
          API_KEY: ${{ secrets.API_KEY }}
